import{a as w,S,i as n}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();function f({query:o="",page:t=1,per_page:l=15}={}){const a=`https://pixabay.com/api/?key=44778240-802eb20b46cf6f3dc26aab8d1&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;return w.get(a,{params:{query:o,page:t,per_page:l}}).then(({data:e})=>e)}function h(o){return o.map(({webformatURL:t,largeImageURL:l,tags:a,likes:e,views:r,comments:c,downloads:C})=>`
      <li class="gallery-item">
      <a class="gallery-link" href="${l}">
      <img class="gallery-img" src="${t}" alt="${a}" />
      <ul class="card-info">
        <li class="card-info-item">
          Likes<span class="accent">${e}</span>
        </li>
        <li class="card-info-item">
          Views<span class="accent">${r}</span>
        </li>
        <li class="card-info-item">
          Comments<span class="accent">${c}</span>
        </li>
        <li class="card-info-item">
          Downloads<span class="accent">${C}</span>
        </li>
      </ul>
      </a>
    </li>`).join("")}const p="/goit-js-hw-12/assets/error-9bc150ed.svg",m="/goit-js-hw-12/assets/caution-4e670f25.svg",g=document.querySelector(".form"),d=document.querySelector(".gallery"),u=document.querySelector(".loader-wrap"),i=document.querySelector(".load-more-btn"),b=new S(".gallery a",{captionsData:"alt",captionDelay:250}),s={query:"",page:1,per_page:15,max_page:0};g.addEventListener("submit",x);async function x(o){if(o.preventDefault(),d.innerHTML="",s.page=1,s.query=g.elements.input.value.trim(),i.style.display="none",i.removeEventListener("click",y),!s.query){n.warning({title:"Caution",titleColor:"white",titleSize:"16px",message:"Please, fill out the field!",messageColor:"white",messageSize:"16px",position:"topRight",backgroundColor:"rgba(255, 160, 0, 0.6)",iconUrl:m,close:!1,closeOnClick:!0}),g.reset();return}u.style.display="flex";try{const t=await f(s);t.hits.length===0?n.error({title:"Error",titleColor:"white",titleSize:"16px",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",messageSize:"16px",position:"bottomRight",backgroundColor:"rgba(239, 64, 64, 0.6)",iconUrl:p,close:!1,closeOnClick:!0}):(s.max_page=Math.ceil(t.totalHits/s.per_page),s.max_page>1?(i.style.display="block",i.addEventListener("click",y)):(i.style.display="none",n.warning({title:"Caution",titleColor:"white",titleSize:"16px",message:"We are sorry, but you have reached the end of search results.",messageColor:"white",messageSize:"16px",position:"bottomCenter",backgroundColor:"rgba(70, 130, 180, 0.8)",iconUrl:m,close:!1,closeOnClick:!0,timeout:6e3})),d.innerHTML=h(t.hits),b.refresh())}catch(t){n.error({title:"Error",titleColor:"white",titleSize:"16px",message:`Ups... Someting went wrong. Error: ${t}`,messageColor:"white",messageSize:"16px",position:"bottomRight",backgroundColor:"rgba(239, 64, 64, 0.6)",iconUrl:p,close:!1,closeOnClick:!0})}finally{g.reset(),u.style.display="none"}}async function y(){s.page+=1,u.style.display="flex",i.style.display="none";try{const o=await f(s);d.insertAdjacentHTML("beforeend",h(o.hits)),b.refresh();//! плавний скролл
const l=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:l*2,behavior:"smooth"})}catch(o){n.error({title:"Error",titleColor:"white",titleSize:"16px",message:`Ups... Someting went wrong. Error: ${o}`,messageColor:"white",messageSize:"16px",position:"bottomRight",backgroundColor:"rgba(239, 64, 64, 0.6)",iconUrl:p,close:!1,closeOnClick:!0})}finally{u.style.display="none",s.page===s.max_page?(i.style.display="none",i.removeEventListener("click",y),n.warning({title:"Caution",titleColor:"white",titleSize:"16px",message:"We are sorry, but you have reached the end of search results.",messageColor:"white",messageSize:"16px",position:"bottomCenter",backgroundColor:"rgba(70, 130, 180, 0.8)",iconUrl:m,close:!1,closeOnClick:!0,timeout:6e3})):i.style.display="block"}}
//# sourceMappingURL=commonHelpers.js.map
